name: 'emissary-action'
description: 'This Github Action allows your contributors to resolve requested changes from a pull request review thread directly from their commit message.'
branding:
  icon: check-square
  color: green
runs:
  using: node16
  main: dist/index.js
inputs:
  token:
    description: 'Github Token'
    required: true
  dryrun:
    description: 'Execute action without replying or resolving any pull request review thread'
    default: 'false'
    required: false
