name: CI
on:
  push:
    paths-ignore:
      - 'tests/fixtures/**.json'

jobs:
  unit-tests:
    name: Test GH action with unit testing
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup NodeJS
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: "16.16.0"

      - name: install dependencies
        run: npm ci

      - name: run tests
        run: npm test -- --ci
  analyze:
    name: Reply to PR review from Commit
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup NodeJS
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: "16.16.0"

      - name: install dependencies
        run: npm ci
      - name: run action
        run: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
