name: Release
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
  tag:
    name: Semantic versioning
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Automatically tag next version
        uses: paulhatch/semantic-version@v5.0.0-alpha2
        with:
          tag_prefix: 'rc'
          major_pattern: '(MAJOR)'
          minor_pattern: '(MINOR)'
          bump_each_commit: false
          search_commit_body: true
          user_format_type: 'csv'
          version_format: 'v${major}.${minor}.${patch}'
