name: Release
on:
  release:
    types: [published, edited]

jobs:
  tag:
    name: Semantic versioning
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
      - name: setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: build and tag action
        uses: JasonEtco/build-and-tag-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
